build-site:
	AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID} \
	API_URL=${API_URL} \
	npm run build && lein minify-assets && lein cljsbuild once min

build-server:
	AUTH0_PUBLIC_KEY=${AUTH0_PUBLIC_KEY} \
	JDBC_DATABASE_URL=${JDBC_DATABASE_URL} \
	FRONTEND_URLS=${FRONTEND_URLS} \
	PORT=${PORT} \
	HOST_URL=${HOST_URL} \
	lein uberjar

dev-site:
	AUTH0_CLIENT_ID=TXEAK5eQSD2ECVStJzdbJPCJ08Q7gWPQ \
	API_URL=http://localhost:3001 \
	lein figwheel

dev-api:
	AUTH0_PUBLIC_KEY="-----BEGIN CERTIFICATE-----MIIDAzCCAeugAwIBAgIJQIk7P6y/E1JUMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNVBAMTFHNhbXVsaXIuZXUuYXV0aDAuY29tMB4XDTE4MTAxMDE0NDMzNFoXDTMyMDYxODE0NDMzNFowHzEdMBsGA1UEAxMUc2FtdWxpci5ldS5hdXRoMC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCkbyFx8dgQwUqGxVYyHS/amrEpPZPSDAWPfeSW+nq2hMVnRNaRdUahUQKy9I3rD5KFZXVTzHjBz9pjXcCtwHxQ7vcAkY+bQvKFQMDmiiBrReHBHbn3SWiGstfiXYMIoQNjLjUURClXRzpzf0u3P+jmFv76EgPAUiS6SZ2IP3mDxENeiYSGzvbhL/Nk8+v/+dWxio0tLGf9jNnADZ6TY2rnHjLOG7trjPoN3T+tZayi3+k1oGLNCRZkFUDOhFk0ygJoD6iv+2Bs1ASTf4brTTh/uWuff7wmmO/QJ4AcxicM0dnJ0EXkWhKoNcH8x5Us+oO5ChF3yZskKRNEW3kBlsCNAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJjhIRD+D7Op5Wqvv33ILM2FjnwOMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAkVxRpzuHrvWcyGPuYXhmEPFxGT82Ge1Qcxd32Djn4IaIxdpV4R/tqx2CHnvVyC/lIbQwfSpXqCGoKp03/6k7BzUIGji1E5o/GDDRjrvsPhX4wAHx7Hz5yQPSsYTUFu0B61v1kUM78RpckCXNZ3friPK5bGzHmZko3fdrC0x4IeOdt2GGHM2VGV+B5reLGAHukC2OPGelPZIjvDxrIVKCoKeVC8LPZl3R/djjy1Zl4rNT6zwTc0Ky9jpSiVxwTIqQfpqwBmduZjU8opWOANpHnL2LMS6FKQPbVPCu8KbBMMCNnmOqGKHhCSXAL5+GI5rkLvbs/xBxEKmInAve5Lvktg==-----END CERTIFICATE-----" \
	JDBC_DATABASE_URL=jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres \
	FRONTEND_URLS=http://localhost:3449 \
	PORT=3001 \
	HOST_URL=http://localhost:3001 \
	lein repl

run-api:
	java ${JVM_OPTS} -cp target/gym.jar clojure.main -m gym.server

deploy-api:
	git push heroku master
